# -*- coding: utf-8 -*-
"""prueba_ragBB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TbcS_JiWTVDSAGOLxMEx48GOUz0Buga7
"""

from src.preproccesing import preprocess_file as pref
from src.data_vector import base_vectorice as bv
from src.agentes import model
from src.tools import retrieve as rt
import os

path_resources = "resources/"  # ajusta si es necesario

files_preprocessed = pref.files_preprocessing(path_resources)
dbvector = bv.create_db_vectorial(files_preprocessed)

llm = model.created_model()

retriever_breb = rt.create_retriever_tool(dbvector["bre-b"], "breb_tool", "Información BRE-B")
retriever_sedes = rt.create_retriever_tool(dbvector["sedes_review"], "sedes_review_tool", "Reviews")
retriever_productos = rt.create_retriever_tool(dbvector["productos"], "productos_tool", "Productos")

def preguntar(pregunta):
    return model.created_agente(
        llm,
        [retriever_breb, retriever_sedes, retriever_productos],
        pregunta
    )

print(preguntar("¿Qué es Bre-B?"))
print(preguntar("¿Qué opinan de la sede Suba?"))